"""Matcher dry run on live markets: `python -m markout.cup dryrun`.

Builds paper contests whose markets copy live Polymarket and Kalshi questions (see
standin.py), excludes each stand-in's own quote, and records which *other-venue* quote
the matcher suggests for each. Writes docs/demo/DRYRUN.md with every suggestion listed so
a reader can judge precision, plus the look-alikes the hard filters now reject (those are
regression tests in tests/test_cup_match_regressions.py).
"""

from __future__ import annotations

import shutil
from datetime import datetime, timezone

from markout import reporting as R
from markout.cup import proposals as P
from markout.cup.paper import PaperContest
from markout.cup.refs import References
from markout.cup.service import Bot
from markout.cup.standin import standin_specs
from markout.cup.store import Store
from markout.paths import DATA, ROOT

OUT = ROOT / "docs" / "demo" / "DRYRUN.md"


def run_one(source: str, n: int = 40, seed: int = 1) -> dict:
    specs, exclude = standin_specs(n=n, seed=seed, source=source)
    work = DATA / "cup" / f"dryrun_{source}"
    shutil.rmtree(work, ignore_errors=True)
    work.mkdir(parents=True)
    api = PaperContest(specs, start_cash=10_000, seed=seed)
    refs = References(live=True, exclude=exclude)
    bot = Bot(api, Store(work / "dry.db"), refs, P.Config(mode="steady"), journal_path=work / "journal.csv")
    info = bot.refresh()
    rows = []
    for s in specs:
        c = s.market.contracts[0]
        ok = [r for r in bot.store.mappings(c.id) if r["score"] > 0]
        top = max(ok, key=lambda r: r["score"]) if ok else None
        rows.append({"question": s.market.title, "category": s.market.category, "own_p": s.truth[c.id],
                     "match": f"{top['source']}: {top['question']} → {top['outcome']}" if top else "",
                     "match_p": top["p"] if top else None, "score": top["score"] if top else None})
    return {"source": source, "n": len(specs), "matched": sum(bool(r["match"]) for r in rows), "rows": rows,
            "pool": len(refs._quotes), "errors": refs.errors, "proposals": info["proposals"]}


def main() -> int:
    res = [run_one("polymarket"), run_one("kalshi")]
    when = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    lines = ["# Matcher dry run on live markets", "",
             f"*Generated by `python -m markout.cup dryrun` on {when}. Stand-in contest markets copy live questions; "
             "each stand-in's own quote is excluded, so a suggestion must come from another market, usually the "
             "other venue. Suggestions still need a human to confirm them in the desk.*", ""]
    for r in res:
        lines += [f"## Stand-ins from {r['source'].title()}", "",
                  f"{r['n']} stand-in markets against a pool of {r['pool']:,} reference quotes: "
                  f"{r['matched']} got a suggestion.", ""]
        hits = [x for x in r["rows"] if x["match"]]
        if hits:
            lines += [R.table(hits, columns=["question", "match", "own_p", "match_p", "score"],
                              headers={"own_p": "stand-in p", "match_p": "reference p"},
                              formats={"own_p": "{:.3f}", "match_p": "{:.3f}", "score": "{:.2f}"}), ""]
        miss = [x["question"] for x in r["rows"] if not x["match"]]
        if miss:
            lines += ["<details><summary>No suggestion</summary>", "", R.bullets(miss), "", "</details>", ""]
    lines += ["## What the hard filters exist for", "",
              "Before them, the matcher's top suggestions on this kind of run were mostly look-alikes: the other "
              "team, another stat line, a different threshold, date or direction, or identical text for a "
              "different game. Each of those is now a regression test "
              "(`tests/test_cup_match_regressions.py`). A missed match costs a trade; a wrong match costs money, "
              "so the filters trade recall for precision and the desk lets you map any market by hand."]
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")
    for r in res:
        print(f"{r['source']}: {r['matched']}/{r['n']} matched (pool {r['pool']:,}; errors {r['errors']})")
    print(f"wrote {OUT}")
    return 0
